version: "3.1"
services:
  db:
    image: postgres:alpine
    container_name: postgres-css
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=commonsurveyservice
    ports:
      - 5438:5432
    restart: always
