spring:
  # Don't print the Spring logo banner at startup (We want only JSON logs printed to stdout)
  main:
    banner-mode: off
  jpa:
    database: POSTGRESQL
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

management:
  endpoints:
    web:
      exposure.include: health, metrics, prometheus
    enable-by-default: true

environment: staging
storage:
  forbruk:
    bucket:
      name: ssb-staging-forbruk-survey-data-kilde